app = "previz-ai-storyboard"
primary_region = "lhr"

[build]

[env]
  PORT = "8080"
  AZURE_STORAGE_ACCOUNT = "dpsbimages"
  AZURE_CONTAINER = "images"
  RUNPOD_ENDPOINT_ID = "b6cpv4fbec236e"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
